version: "3"
services:
  fernsehrat:
    ports:
      - "8089:8080"
    volumes:
      - ./downloads:/app/downloads
    restart: always
    image: ghcr.io/anjomro/fernsehrat:v1.0.0
    build:
      context: .
    container_name: fernsehrat
    environment:
      - SERVER_DOWNLOAD=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 10s
      retries: 10